adding chapter 3
mine-cetinkaya-rundel/r4ds-solutions pull request #3
Opened 2023-03-20 16:43 UTC by jabirG

adding chapter 3 for review

2023-03-20 18:03 UTC, jabirG reviewed
my review

2023-03-20 18:03 UTC, jabirG commented on chapter-3.qmd
> +  geom_point(mapping = aes(x = displ, y = hwy))
```suggestion
  geom_point( aes(x = displ, y = hwy))
```

2023-03-27 16:19 UTC, mine-cetinkaya-rundel commented on chapter-3.qmd
> +2.tweak each of th R commands so they run properly
```suggestion
2. Tweak each of the R commands so they run properly.
```

2023-03-27 16:19 UTC, mine-cetinkaya-rundel commented on chapter-3.qmd
> +
Remove this space

2023-03-27 16:20 UTC, mine-cetinkaya-rundel commented on chapter-3.qmd
> +
Remove extraneous spaces.

2023-03-27 16:20 UTC, mine-cetinkaya-rundel commented on chapter-3.qmd
> +pulls up keyboard shortcuts
Capitalization and period at the end of sentence.

2023-04-14 18:21 UTC, mine-cetinkaya-rundel requested changes

2023-04-14 18:21 UTC, mine-cetinkaya-rundel commented on chapter-3.qmd
> +1. Because in "my_variable" theres a 1 instead of an i in variable.
```suggestion
1. Because in `my_variable` theres a ı (i without a dot) instead of an i in variable name.
```

2023-04-14 18:21 UTC, mine-cetinkaya-rundel commented on chapter-3.qmd
> +2.
This is missing the library() function and the geom_smooth() layer.

2023-04-14 18:21 UTC, mine-cetinkaya-rundel commented on chapter-3.qmd
> +3. Alt + Shift + K Pulls up keyboard shortcuts.
```suggestion
3. Alt + Shift + K pulls up keyboard shortcuts.
```

2023-04-14 18:21 UTC, mine-cetinkaya-rundel commented on chapter-3.qmd
> +4. The "my_bar_plot" is saved because thats what was specified.
```suggestion
4. The `my_bar_plot` object is saved because that's what was specified in the `plot` argument of the `ggsave()` call.
```

2023-04-26 04:28 UTC, merged