chapter 6
mine-cetinkaya-rundel/r4ds-solutions pull request #6
Opened 2023-03-27 18:07 UTC by jabirG

2023-03-27 18:24 UTC, jabirG commented on chapter-6.qmd
> +1.Using prose, describe how the variables and observations are organised in each of the sample tables
```suggestion
1.Using prose, describe how the variables and observations are organised in each of the sample tables.
```

2023-03-27 18:24 UTC, jabirG commented on chapter-6.qmd
> +
```suggestion
```

2023-03-27 18:24 UTC, jabirG commented on chapter-6.qmd
> +
```suggestion
```

2023-03-28 20:54 UTC, mine-cetinkaya-rundel requested changes

2023-03-28 20:54 UTC, mine-cetinkaya-rundel commented on chapter-6.qmd
> +##Solutions
Remove these

2023-03-28 20:54 UTC, mine-cetinkaya-rundel commented on chapter-6.qmd
> +1.Using prose, describe how the variables and observations are organised in each of the sample tables.
This question is not answered?

2023-03-28 20:54 UTC, mine-cetinkaya-rundel commented on chapter-6.qmd
> +2.
Some of these questions are not answered. Can you organize it so that each part is answered underneath its label?

2023-06-21 20:12 UTC, merged

2023-06-21 20:17 UTC, mine-cetinkaya-rundel commented
Thank you @jabirG -- answer updates at c1865975577018d26b394b457509a6faf7f81499 if you'd like to review!